<?php

/**
 * @file
 * Contains single_counter.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function pw_single_counter_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the single_counter module.
    case 'help.page.pw_single_counter':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provide paragraph counter contains 2 fields') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function pw_single_counter_theme($existing, $type, $theme, $path) {
  return [
    'field__paragraph__field_pw_number__pw_single_counter' => [
      'base hook' => 'field',
    ],
    'field__paragraph__field_pw_title__pw_single_counter' => [
      'base hook' => 'field',
    ],
    'paragraph__pw_single_counter' => [
      'base hook' => 'paragraph',
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function pw_single_counter_preprocess_paragraph(&$variables) {
  $paragraph = $variables['paragraph'];
  $bundle = $paragraph->bundle();

  switch ($bundle) {
    case 'pw_single_counter':
     // $variables['#attached']['library'][] = 'counters/counters';
  }
}

/**
 * Implements hook_preprocess_field().
 */
function pw_single_counter_preprocess_field(&$variables) {
  if ($variables['element']['#entity_type'] == 'paragraph') {
    if ($variables['element']['#bundle'] == 'pw_single_counter') {
      if ($variables['field_name'] == 'field_pw_number') {

        $num_array = $variables['element']['#object']->get('field_pw_number')->getValue();

        $variables['column_class'] = 'col-sm-4';
        if (!empty($num_array[0]['value'])) {
          $variables['column_class'] = $num_array[0]['value'];

        }
      }
    }
  }
}


